services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cafe'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./.data:/var/lib/postgresql/data
